export enum actions {
  USER_SIGNIN,
  USER_SIGNOUT,
  USER_GET,
  USER_CREATE,
  WALLET_GET,
  WALLET_GET_ALL,
  WALLET_CREATE,
  WALLET_UPDATE,
  WALLET_DELETE,
  CURRENCY_GET_ALL
}

export const baseUrl = "http://159.89.107.178:3001/";
