export enum actions {
  USER_SIGNIN,
  USER_SIGNOUT,
  USER_GET,
  USER_CREATE,
  WALLET_GET,
  WALLET_GET_ALL,
  WALLET_CREATE,
  WALLET_UPDATE,
  WALLET_DELETE,
  CURRENCY_GET_ALL,
  CATEGORY_GET,
  CATEGORY_GET_ALL,
  CATEGORY_CREATE,
  CATEGORY_UPDATE,
  CATEGORY_DELETE
}

export const baseUrl = `${process.env.HOST}:${process.env.PORT}/`;
