version: "3.1"

services:
  server:
    build: .
    ports:
      - 3001:3001
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    depends_on:
      - server
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
