version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
