version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./api/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
